spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loan_application_db
    username: root
    password: root
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
     # use-new-id-generator-mappings: false


